SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

CREATE TABLE roles (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(80) NOT NULL, slug VARCHAR(80) NOT NULL UNIQUE, status ENUM('active','inactive') NOT NULL DEFAULT 'active', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted_at DATETIME NULL) ENGINE=InnoDB;
CREATE TABLE permissions (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL, slug VARCHAR(120) NOT NULL UNIQUE, status ENUM('active','inactive') NOT NULL DEFAULT 'active', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE users (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(150) NOT NULL, email VARCHAR(190) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL, status ENUM('active','inactive','blocked') NOT NULL DEFAULT 'active', failed_login_attempts SMALLINT UNSIGNED NOT NULL DEFAULT 0, locked_until DATETIME NULL, last_login_at DATETIME NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted_at DATETIME NULL, INDEX idx_users_status(status)) ENGINE=InnoDB;
CREATE TABLE role_permissions (role_id BIGINT UNSIGNED NOT NULL, permission_id BIGINT UNSIGNED NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(role_id,permission_id), FOREIGN KEY(role_id) REFERENCES roles(id) ON DELETE CASCADE, FOREIGN KEY(permission_id) REFERENCES permissions(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE user_roles (user_id BIGINT UNSIGNED NOT NULL, role_id BIGINT UNSIGNED NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(user_id,role_id), FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE, FOREIGN KEY(role_id) REFERENCES roles(id) ON DELETE CASCADE) ENGINE=InnoDB;

CREATE TABLE categories (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, parent_id BIGINT UNSIGNED NULL, name VARCHAR(150) NOT NULL, slug VARCHAR(170) NOT NULL UNIQUE, description TEXT NULL, sort_order INT NOT NULL DEFAULT 0, status ENUM('draft','published','archived') NOT NULL DEFAULT 'draft', seo_title VARCHAR(190) NULL, seo_description VARCHAR(320) NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted_at DATETIME NULL, FOREIGN KEY(parent_id) REFERENCES categories(id) ON DELETE SET NULL, INDEX idx_categories_status_sort(status,sort_order)) ENGINE=InnoDB;
CREATE TABLE segments (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(150) NOT NULL, slug VARCHAR(170) NOT NULL UNIQUE, summary TEXT NULL, content LONGTEXT NULL, needs LONGTEXT NULL, challenges LONGTEXT NULL, featured_image VARCHAR(255) NULL, sort_order INT NOT NULL DEFAULT 0, status ENUM('draft','published','archived') NOT NULL DEFAULT 'draft', seo_title VARCHAR(190) NULL, seo_description VARCHAR(320) NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted_at DATETIME NULL, INDEX idx_segments_status_sort(status,sort_order)) ENGINE=InnoDB;
CREATE TABLE products (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(190) NOT NULL, slug VARCHAR(210) NOT NULL UNIQUE, summary TEXT NULL, description LONGTEXT NULL, features JSON NULL, benefits JSON NULL, voltages VARCHAR(255) NULL, power_range VARCHAR(255) NULL, protection_rating VARCHAR(80) NULL, optional_components JSON NULL, featured_image VARCHAR(255) NULL, sort_order INT NOT NULL DEFAULT 0, featured TINYINT(1) NOT NULL DEFAULT 0, status ENUM('draft','published','archived') NOT NULL DEFAULT 'draft', published_at DATETIME NULL, seo_title VARCHAR(190) NULL, seo_description VARCHAR(320) NULL, created_by BIGINT UNSIGNED NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted_at DATETIME NULL, FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL, INDEX idx_products_publish(status,published_at), INDEX idx_products_featured(featured,sort_order), FULLTEXT INDEX ft_products(name,summary,description)) ENGINE=InnoDB;
CREATE TABLE product_categories (product_id BIGINT UNSIGNED NOT NULL, category_id BIGINT UNSIGNED NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(product_id,category_id), FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE, FOREIGN KEY(category_id) REFERENCES categories(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE product_images (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, product_id BIGINT UNSIGNED NOT NULL, path VARCHAR(255) NOT NULL, alt_text VARCHAR(255) NULL, sort_order INT NOT NULL DEFAULT 0, status ENUM('active','inactive') NOT NULL DEFAULT 'active', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted_at DATETIME NULL, FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE, INDEX idx_product_images(product_id,sort_order)) ENGINE=InnoDB;
CREATE TABLE product_specifications (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, product_id BIGINT UNSIGNED NOT NULL, label VARCHAR(150) NOT NULL, value VARCHAR(500) NOT NULL, sort_order INT NOT NULL DEFAULT 0, status ENUM('active','inactive') NOT NULL DEFAULT 'active', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE product_applications (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, product_id BIGINT UNSIGNED NOT NULL, name VARCHAR(190) NOT NULL, sort_order INT NOT NULL DEFAULT 0, status ENUM('active','inactive') NOT NULL DEFAULT 'active', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE product_segments (product_id BIGINT UNSIGNED NOT NULL, segment_id BIGINT UNSIGNED NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(product_id,segment_id), FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE, FOREIGN KEY(segment_id) REFERENCES segments(id) ON DELETE CASCADE) ENGINE=InnoDB;

CREATE TABLE services (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(190) NOT NULL, slug VARCHAR(210) NOT NULL UNIQUE, summary TEXT NULL, content LONGTEXT NULL, featured_image VARCHAR(255) NULL, sort_order INT NOT NULL DEFAULT 0, status ENUM('draft','published','archived') NOT NULL DEFAULT 'draft', seo_title VARCHAR(190) NULL, seo_description VARCHAR(320) NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted_at DATETIME NULL, INDEX idx_services_status_sort(status,sort_order)) ENGINE=InnoDB;
CREATE TABLE projects (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, title VARCHAR(190) NOT NULL, slug VARCHAR(210) NOT NULL UNIQUE, client_name VARCHAR(190) NULL, segment_id BIGINT UNSIGNED NULL, location VARCHAR(190) NULL, project_year YEAR NULL, summary TEXT NULL, challenge LONGTEXT NULL, solution LONGTEXT NULL, result LONGTEXT NULL, cover_image VARCHAR(255) NULL, status ENUM('draft','published','archived') NOT NULL DEFAULT 'draft', published_at DATETIME NULL, seo_title VARCHAR(190) NULL, seo_description VARCHAR(320) NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted_at DATETIME NULL, FOREIGN KEY(segment_id) REFERENCES segments(id) ON DELETE SET NULL, INDEX idx_projects_filters(status,segment_id,project_year)) ENGINE=InnoDB;
CREATE TABLE project_images (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, project_id BIGINT UNSIGNED NOT NULL, path VARCHAR(255) NOT NULL, alt_text VARCHAR(255) NULL, sort_order INT NOT NULL DEFAULT 0, status ENUM('active','inactive') NOT NULL DEFAULT 'active', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE project_products (project_id BIGINT UNSIGNED NOT NULL, product_id BIGINT UNSIGNED NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(project_id,product_id), FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE, FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE) ENGINE=InnoDB;

CREATE TABLE authors (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NULL, name VARCHAR(150) NOT NULL, slug VARCHAR(170) NOT NULL UNIQUE, bio TEXT NULL, photo VARCHAR(255) NULL, status ENUM('active','inactive') NOT NULL DEFAULT 'active', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted_at DATETIME NULL, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB;
CREATE TABLE posts (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, author_id BIGINT UNSIGNED NULL, title VARCHAR(220) NOT NULL, slug VARCHAR(240) NOT NULL UNIQUE, excerpt TEXT NULL, content LONGTEXT NULL, featured_image VARCHAR(255) NULL, reading_time SMALLINT UNSIGNED NULL, status ENUM('draft','scheduled','published','archived') NOT NULL DEFAULT 'draft', published_at DATETIME NULL, seo_title VARCHAR(190) NULL, seo_description VARCHAR(320) NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted_at DATETIME NULL, FOREIGN KEY(author_id) REFERENCES authors(id) ON DELETE SET NULL, INDEX idx_posts_publish(status,published_at), FULLTEXT INDEX ft_posts(title,excerpt,content)) ENGINE=InnoDB;
CREATE TABLE post_categories (post_id BIGINT UNSIGNED NOT NULL, category_id BIGINT UNSIGNED NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(post_id,category_id), FOREIGN KEY(post_id) REFERENCES posts(id) ON DELETE CASCADE, FOREIGN KEY(category_id) REFERENCES categories(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE tags (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL, slug VARCHAR(120) NOT NULL UNIQUE, status ENUM('active','inactive') NOT NULL DEFAULT 'active', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted_at DATETIME NULL) ENGINE=InnoDB;
CREATE TABLE post_tags (post_id BIGINT UNSIGNED NOT NULL, tag_id BIGINT UNSIGNED NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(post_id,tag_id), FOREIGN KEY(post_id) REFERENCES posts(id) ON DELETE CASCADE, FOREIGN KEY(tag_id) REFERENCES tags(id) ON DELETE CASCADE) ENGINE=InnoDB;

CREATE TABLE leads (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, protocol VARCHAR(40) NOT NULL UNIQUE, name VARCHAR(150) NOT NULL, company VARCHAR(190) NULL, cnpj VARCHAR(18) NULL, email VARCHAR(190) NOT NULL, phone VARCHAR(30) NOT NULL, whatsapp VARCHAR(30) NULL, city VARCHAR(120) NULL, state CHAR(2) NULL, segment_id BIGINT UNSIGNED NULL, product_id BIGINT UNSIGNED NULL, voltage VARCHAR(80) NULL, power VARCHAR(100) NULL, quantity INT UNSIGNED NOT NULL DEFAULT 1, desired_deadline DATE NULL, description TEXT NOT NULL, lgpd_consent TINYINT(1) NOT NULL, status ENUM('new','analysis','waiting_information','preparing','quote_sent','negotiation','approved','lost','completed') NOT NULL DEFAULT 'new', assigned_to BIGINT UNSIGNED NULL, source VARCHAR(80) NOT NULL DEFAULT 'website', internal_notes TEXT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted_at DATETIME NULL, FOREIGN KEY(segment_id) REFERENCES segments(id) ON DELETE SET NULL, FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE SET NULL, FOREIGN KEY(assigned_to) REFERENCES users(id) ON DELETE SET NULL, INDEX idx_leads_pipeline(status,assigned_to,created_at), INDEX idx_leads_email(email)) ENGINE=InnoDB;
CREATE TABLE lead_files (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, lead_id BIGINT UNSIGNED NOT NULL, original_name VARCHAR(255) NOT NULL, stored_name VARCHAR(255) NOT NULL UNIQUE, mime_type VARCHAR(120) NOT NULL, size_bytes BIGINT UNSIGNED NOT NULL, file_type ENUM('diagram','specification','photo','other') NOT NULL, status ENUM('active','quarantined','deleted') NOT NULL DEFAULT 'active', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted_at DATETIME NULL, FOREIGN KEY(lead_id) REFERENCES leads(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE lead_history (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, lead_id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED NULL, from_status VARCHAR(40) NULL, to_status VARCHAR(40) NULL, note TEXT NULL, status ENUM('active','hidden') NOT NULL DEFAULT 'active', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY(lead_id) REFERENCES leads(id) ON DELETE CASCADE, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL, INDEX idx_lead_history(lead_id,created_at)) ENGINE=InnoDB;
CREATE TABLE contacts (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(150) NOT NULL, company VARCHAR(190) NULL, email VARCHAR(190) NOT NULL, phone VARCHAR(30) NULL, department VARCHAR(100) NULL, reason VARCHAR(150) NULL, message TEXT NOT NULL, status ENUM('new','in_progress','answered','closed','spam') NOT NULL DEFAULT 'new', assigned_to BIGINT UNSIGNED NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted_at DATETIME NULL, FOREIGN KEY(assigned_to) REFERENCES users(id) ON DELETE SET NULL, INDEX idx_contacts_status(status,created_at)) ENGINE=InnoDB;

CREATE TABLE site_settings (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, setting_key VARCHAR(150) NOT NULL UNIQUE, setting_value LONGTEXT NULL, value_type ENUM('string','text','number','boolean','json') NOT NULL DEFAULT 'string', group_name VARCHAR(80) NOT NULL DEFAULT 'general', status ENUM('active','inactive') NOT NULL DEFAULT 'active', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted_at DATETIME NULL) ENGINE=InnoDB;
CREATE TABLE banners (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, title VARCHAR(220) NOT NULL, subtitle TEXT NULL, image_path VARCHAR(255) NULL, mobile_image_path VARCHAR(255) NULL, primary_label VARCHAR(100) NULL, primary_url VARCHAR(255) NULL, secondary_label VARCHAR(100) NULL, secondary_url VARCHAR(255) NULL, sort_order INT NOT NULL DEFAULT 0, starts_at DATETIME NULL, ends_at DATETIME NULL, status ENUM('draft','published','archived') NOT NULL DEFAULT 'draft', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted_at DATETIME NULL) ENGINE=InnoDB;
CREATE TABLE testimonials (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, author_name VARCHAR(150) NOT NULL, company_name VARCHAR(190) NULL, role_name VARCHAR(120) NULL, content TEXT NOT NULL, consent_recorded_at DATETIME NULL, sort_order INT NOT NULL DEFAULT 0, status ENUM('draft','published','archived') NOT NULL DEFAULT 'draft', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted_at DATETIME NULL) ENGINE=InnoDB;
CREATE TABLE downloads (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, product_id BIGINT UNSIGNED NULL, title VARCHAR(190) NOT NULL, path VARCHAR(255) NOT NULL, mime_type VARCHAR(120) NOT NULL, size_bytes BIGINT UNSIGNED NOT NULL, sort_order INT NOT NULL DEFAULT 0, status ENUM('active','inactive') NOT NULL DEFAULT 'active', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted_at DATETIME NULL, FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE media (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, uploaded_by BIGINT UNSIGNED NULL, original_name VARCHAR(255) NOT NULL, stored_name VARCHAR(255) NOT NULL UNIQUE, path VARCHAR(255) NOT NULL, mime_type VARCHAR(120) NOT NULL, size_bytes BIGINT UNSIGNED NOT NULL, width INT UNSIGNED NULL, height INT UNSIGNED NULL, alt_text VARCHAR(255) NULL, status ENUM('active','quarantined','deleted') NOT NULL DEFAULT 'active', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted_at DATETIME NULL, FOREIGN KEY(uploaded_by) REFERENCES users(id) ON DELETE SET NULL, INDEX idx_media_type(mime_type,status)) ENGINE=InnoDB;
CREATE TABLE activity_logs (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NULL, action VARCHAR(120) NOT NULL, entity_type VARCHAR(100) NULL, entity_id BIGINT UNSIGNED NULL, ip_hash CHAR(64) NULL, user_agent VARCHAR(500) NULL, metadata JSON NULL, status ENUM('success','failure') NOT NULL DEFAULT 'success', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL, INDEX idx_activity_entity(entity_type,entity_id), INDEX idx_activity_created(created_at)) ENGINE=InnoDB;
CREATE TABLE password_resets (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL, token_hash CHAR(64) NOT NULL UNIQUE, expires_at DATETIME NOT NULL, used_at DATETIME NULL, status ENUM('pending','used','expired','revoked') NOT NULL DEFAULT 'pending', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE, INDEX idx_password_resets(user_id,status,expires_at)) ENGINE=InnoDB;

INSERT INTO roles (name,slug) VALUES ('Superadministrador','superadmin'),('Administrador','admin'),('Comercial','sales'),('Marketing','marketing'),('Editor','editor');
INSERT INTO permissions (name,slug) VALUES ('Gerenciar usuários','users.manage'),('Gerenciar produtos','products.manage'),('Gerenciar conteúdo','content.manage'),('Gerenciar leads','leads.manage'),('Gerenciar configurações','settings.manage');
INSERT INTO categories (name,slug,status,sort_order) VALUES ('Painéis de comando','paineis-de-comando','published',1),('Painéis de distribuição','paineis-de-distribuicao','published',2),('Centro de Controle de Motores','ccm','published',3),('Automação industrial','automacao-industrial','published',4),('Projetos especiais','projetos-especiais','published',5);
INSERT INTO segments (name,slug,summary,status,sort_order) VALUES ('Indústria','industria','CONTEÚDO DEMONSTRATIVO — substituir por conteúdo validado.','published',1),('Saneamento','saneamento','CONTEÚDO DEMONSTRATIVO — substituir por conteúdo validado.','published',2),('Irrigação','irrigacao','CONTEÚDO DEMONSTRATIVO — substituir por conteúdo validado.','published',3);
INSERT INTO products (name,slug,summary,description,status,featured,sort_order) VALUES ('Painel de comando personalizado','painel-de-comando-personalizado','DADO DEMONSTRATIVO — solução configurada conforme a aplicação.','Conteúdo técnico demonstrativo para validação e substituição antes da publicação.','published',1,1),('Centro de Controle de Motores','centro-de-controle-de-motores','DADO DEMONSTRATIVO — centralização de acionamentos e proteção.','Conteúdo técnico demonstrativo para validação e substituição antes da publicação.','published',1,2);

SET FOREIGN_KEY_CHECKS=1;
