import type { FormEvent } from 'react';
import { Icon } from '../components/common/Icon';
import { companyConfig } from '../constants/company';

export function TechnicalTicketPage() {
  const submit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const data = new FormData(event.currentTarget);
    const message = ['Olá! Gostaria de abrir um atendimento técnico.', `Nome: ${data.get('name')}`, `Empresa: ${data.get('company') || 'Não informada'}`, `E-mail: ${data.get('email')}`, `WhatsApp: ${data.get('phone')}`, `Produto: ${data.get('product')}`, `Potência: ${data.get('power') || 'Não informada'}`, `Tensão: ${data.get('voltage') || 'Não informada'}`, `Aplicação: ${data.get('application')}`, `Mensagem: ${data.get('message')}`].join('\n');
    window.open(`https://wa.me/${companyConfig.whatsapp}?text=${encodeURIComponent(message)}`, '_blank', 'noopener,noreferrer');
  };
  return <section className="technical-ticket"><div className="container technical-ticket__layout"><div><span>Ticket técnico</span><h1>Envie os dados da aplicação direto para o WhatsApp.</h1><p>Preencha as informações principais. Ao enviar, a mensagem será aberta pronta no WhatsApp da Painel de Comando.</p><a href={`mailto:${companyConfig.email}`}>{companyConfig.email}</a></div><form onSubmit={submit}><label>Nome<input name="name" required autoComplete="name"/></label><label>Empresa<input name="company" autoComplete="organization"/></label><label>E-mail<input name="email" type="email" required autoComplete="email"/></label><label>WhatsApp<input name="phone" type="tel" required autoComplete="tel" placeholder="+55 11 99999-9999"/></label><label>Produto<select name="product" defaultValue="Painel Estrela Triângulo 15CV"><option>Painel Estrela Triângulo 15CV</option><option>Painel com Soft Starter</option><option>Painel com Inversor de Frequência</option><option>Painel para Bombas</option><option>Projeto personalizado</option></select></label><label>Assunto<select name="subject" defaultValue="Suporte técnico"><option>Suporte técnico</option><option>Orçamento</option><option>Garantia</option><option>Troca ou devolução</option></select></label><label>Potência do motor<input name="power" placeholder="Ex.: 15 CV / 11 kW"/></label><label>Tensão disponível<input name="voltage" placeholder="Ex.: 220 V / 380 V"/></label><label className="technical-ticket__wide">Aplicação<textarea name="application" required placeholder="Ex.: bomba, esteira, ventilador, máquina industrial"/></label><label className="technical-ticket__wide">Mensagem<textarea name="message" required placeholder="Descreva o que precisa: orçamento, prazo, suporte técnico..."/></label><button className="button button--primary technical-ticket__wide" type="submit"><Icon name="whatsapp" size={20}/> Abrir atendimento no WhatsApp</button></form></div></section>;
}
